# Файл docker-compose.yml для InfluxDB и Telegraf

version: '3.8'

services:
  # Сервис базы данных InfluxDB
  influxdb:
    image: influxdb:2.7.6
    container_name: digitalegiz-influx
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Aa31415926
      - DOCKER_INFLUXDB_INIT_ORG=dtkaznu
      - DOCKER_INFLUXDB_INIT_BUCKET=iot-data
    networks:
      - digital-egiz

  # Сервис сбора данных Telegraf
  telegraf:
    image: telegraf:1.30.1
    container_name: digitalegiz-telegraf
    restart: unless-stopped
    volumes:
      # Пробрасываем наш файл конфигурации внутрь
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - digital-egiz

# Определяем нашу общую сеть как внешнюю
networks:
  digital-egiz:
    external: true